/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/dashboard/AboutUs.vue')['default']
    Advantage: typeof import('./src/components/dashboard/Advantage.vue')['default']
    Business: typeof import('./src/components/dashboard/Business.vue')['default']
    ChooseUs: typeof import('./src/components/dashboard/ChooseUs.vue')['default']
    CustomBanner: typeof import('./src/components/customBanner/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HeaderDeskDrawer: typeof import('./src/components/layout/HeaderDeskDrawer.vue')['default']
    Hero: typeof import('./src/components/dashboard/Hero.vue')['default']
    Partners: typeof import('./src/components/dashboard/Partners.vue')['default']
    Process: typeof import('./src/components/dashboard/Process.vue')['default']
    Product: typeof import('./src/components/dashboard/Product.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Vision: typeof import('./src/components/dashboard/Vision.vue')['default']
  }
}
