/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/dashboard/AboutUs.vue')['default']
    Advantage: typeof import('./src/components/dashboard/Advantage.vue')['default']
    Business: typeof import('./src/components/dashboard/Business.vue')['default']
    ChooseUs: typeof import('./src/components/dashboard/ChooseUs.vue')['default']
    CompanyHonor: typeof import('./src/components/more/CompanyHonor.vue')['default']
    CompanyPatent: typeof import('./src/components/more/CompanyPatent.vue')['default']
    ContactUs: typeof import('./src/components/contactUs/index.vue')['default']
    CorporateCulture: typeof import('./src/components/more/CorporateCulture.vue')['default']
    CustomBanner: typeof import('./src/components/customBanner/index.vue')['default']
    DeskDrawer: typeof import('./src/components/layout/DeskDrawer.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    HeaderDeskDrawer: typeof import('./src/components/layout/HeaderDeskDrawer.vue')['default']
    Hero: typeof import('./src/components/dashboard/Hero.vue')['default']
    LoveActivity: typeof import('./src/components/more/LoveActivity.vue')['default']
    Partners: typeof import('./src/components/dashboard/Partners.vue')['default']
    Process: typeof import('./src/components/dashboard/Process.vue')['default']
    Product: typeof import('./src/components/dashboard/Product.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Vision: typeof import('./src/components/dashboard/Vision.vue')['default']
  }
}
